### ISSUE TITLE
Acces a la BD 

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#4]
Je peux modifier le nom/Prenom de l'auteur dans la form AuthorAndMoviesForm, 
en faisant mettre a jour à la BD j'ai rentré une données fausse.

**Comment by Neskyte** [comment]
A la base je pensais que cela faisait partie de l'énoncé..

J'ai rendu les champs qui ne sont pas sensé être modifiable dans la fenêtre "enabled = false", et ai modifié la BL, la DAL et la SP en fonction afin que les changements ne puissent être effectués.
