### ISSUE TITLE
Nouvel Auteur affichage vide

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#5]
J'ai creer un nouvel auteur dans la BD et je lui ai assigné un film mais la ComboBOx m'affiche vide quand j'ouvre la form AutheurAndMovie

**Comment by Neskyte** [comment]
Tu peux rééssayer avec le dernier commit ? tout semble fonctionner normalement ici. (commit e1990ede)

**Comment by EmixamZ** [comment]
All ok, je ferme le ticket.
