### ISSUE TITLE
Erreur SQL Generer

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#6]
Je peux generer une erreur SQL en modifiant le nom de l'auteur avec un nom/Prenom existant

**Comment by Neskyte** [comment]
Ne pause plus de probleme étant donné que l'édition des auteurs est bloquée.

**Comment by Neskyte** [comment]
Par contre j'ai géré l'exception dans le cas où on tenterait d'update un film alors qu'il y en a déja un avec un libéllé donné
