### ISSUE TITLE
Exception non gerer

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#7]
Lorsque la ComboBox box est vide, et que je modifier un auteur j'ai une erreur non gerer car aucun film n'est associé a l'update
![capture](https://user-images.githubusercontent.com/36507640/47872428-dccb0080-de0e-11e8-83c2-5ddaee57c77d.PNG)

**Comment by EmixamZ** [comment]
Je peux generer la même erreur en faisant : 

Je vais dans la forme des films et en meme temps dans les films auteur

Je supprime les films et les auteurs, je reviens dans la fenetre film auteur, j'affiche l'auteur et j'essaye de lui rajouter un film. Bug car il n'existe plus. 

Non gérée !

**Comment by Neskyte** [comment]
Tu peux rééssayer à présent ?

**Comment by EmixamZ** [comment]
Tout ok si tu rajoute l'evenement : 

private void FilmId_comboBox_KeyDown(object sender, KeyEventArgs e)
        {

            e.SuppressKeyPress = true;

        }
