### ISSUE TITLE
Edit possible dans la form ShowAuthorsFromOneMovieForm

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#8]
Edit possible dans la form ShowAuthorsFromOneMovieForm

**Comment by Neskyte** [comment]
Comment ca ?

**Comment by EmixamZ** [comment]
![snip](https://user-images.githubusercontent.com/36507640/47967888-c5845100-e062-11e8-8c9e-c3f423c6be1b.PNG)

Ton ID est modifiable dans le dataGrid View et donc je peux rentrer un string au lieu d'un int et generer une erreur non-custom.

Je remarque aussi que si je selectionne le film id = 7 et que j'affiche l'auteur, 
Ce même auteur a un film id = 0 au lieu de 7 .

**Comment by EmixamZ** [comment]
Je creer une autre issue pour le deuxième problème.

**Comment by Neskyte** [comment]
Bizzare, j'arrive pas a reproduire ces erreurs... Tu as recloné le répo ?

**Comment by Neskyte** [comment]
Ok c'est bon je corrige, j'ai trouvé
