### ISSUE TITLE
Auteur avec film id = 0

### ISSUE THREAD

**Issue by EmixamZ** [Neskyte/SGBD_DEVOIR3_07-11-2018#9]
Peu importe quel film je selectionne et qui affiche l'auteur, 
Le film id est a 0 au lieu de l'id du film selectionné.

**Comment by EmixamZ** [comment]
Ex: 
![snip2](https://user-images.githubusercontent.com/36507640/47967923-5eb36780-e063-11e8-9283-efe3a071c95f.PNG)

**Comment by Neskyte** [comment]
Du à un oubli de fetch prenom et film id du DataReader dans le Model de l'auteur au niveau de la DAL.
